alter table patient
drop constraint patient_medical_staff_id_fk;
drop table contact;
drop table address;
drop table medical_staff;
drop table disinfection_schedule;
drop table ward;
drop table department;
drop table diagnosis;
drop table hospitalization;
drop table patient;
drop type if exists sex;
drop type if exists patient_status;
drop type if exists hospitalization_type;
drop type if exists diagnosis_status;
drop type if exists service;
drop type if exists ward_type;
drop type if exists medical_qualification;
drop type if exists medical_specialization;
drop type if exists medical_profile;