insert into ward (number, capacity, service, type, created_at, updated_at) VALUES
('№1', 1, 'vip'::service, 'обычный'::ward_type, (now() - interval '7 year'), (now() - interval '7 year')),
('№2', 1, 'vip'::service, 'реанимация'::ward_type, (now() - interval '7 year'), (now() - interval '7 year')),
('№3', 1, 'vip'::service, 'обычный'::ward_type, (now() - interval '7 year'), (now() - interval '7 year')),
('№4', 10, 'обычный'::service, 'обычный'::ward_type, (now() - interval '7 year'), (now() - interval '7 year')),
('№5', 6, 'обычный'::service, 'реанимация'::ward_type, (now() - interval '7 year'), (now() - interval '7 year')),
('№6', 5, 'обычный'::service, 'реанимация'::ward_type, (now() - interval '7 year'), (now() - interval '7 year')),
('№7', 15, 'обычный'::service, 'обычный'::ward_type, (now() - interval '7 year'), (now() - interval '7 year')),
('№8', 12, 'обычный'::service, 'обычный'::ward_type, (now() - interval '7 year'), (now() - interval '7 year')),
('№9', 10, 'обычный'::service, 'обычный'::ward_type, (now() - interval '7 year'), (now() - interval '7 year')),
('№10', 10, 'обычный'::service, 'реанимация'::ward_type, (now() - interval '7 year'), (now() - interval '7 year')),
('№11', 10, 'обычный'::service, 'обычный'::ward_type, (now() - interval '7 year'), (now() - interval '7 year')),
('№12', 2, 'комфортный'::service, 'реанимация'::ward_type, (now() - interval '7 year'), (now() - interval '7 year')),
('№13', 2, 'комфортный'::service, 'обычный'::ward_type, (now() - interval '7 year'), (now() - interval '7 year')),
('№14', 2, 'комфортный'::service, 'обычный'::ward_type, (now() - interval '7 year'), (now() - interval '7 year')),
('№15', 2, 'комфортный'::service, 'реанимация'::ward_type, (now() - interval '7 year'), (now() - interval '7 year'));